# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release Application to the Google Cloud Platform

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    
    - name: Use Node.js 18
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    
    - name: clean install all dependencies
      run: npm install
    
    - name: build the application
      run: npm run build:prod
    
    - name: google cloud platform auth
      uses: google-github-actions/auth@v1.0.0
      with:
        credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}'
    
    - name: setup google cloud platform cli
      uses: google-github-actions/setup-gcloud@v1.0.0

    - name: deploy app to google cloud
      run: gcloud app deploy --stop-previous-version